use_frameworks!

target 'RxQRScanner_Example' do
  platform :ios, '9.0'
  pod 'RxSwift',    '~> 4.3'
  pod 'RxCocoa',    '~> 4.3'
  pod 'RxQRScanner', :path => '../'

  target 'RxQRScanner_Tests' do
    inherit! :search_paths
  end
end
