use_frameworks!

target 'RxQRScanner_Example' do
	platform :ios, '9.0'
	pod 'TinyConstraints'
	pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxQRScanner', :path => '../'

  target 'RxQRScanner_Tests' do
    inherit! :search_paths

    
  end
end
